
language: python
python:
  - "2.7"

sudo: required

branches:
  only:

before_install: 
  - sudo apt-get install gfortran
  - sudo apt-get install valgrind
  - pip install scipy
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install recommonmark
  - pip install matplotlib
  - pip install pytest-cov
  - pip install codecov
#  - pip install cpp-coveralls
#  - pip install coveralls
#  - sudo apt-get install -y lcov
#  - gem install coveralls-lcov
  - pip install -e .

install: 

script:
  - gfortran -Wall -Werror aronnax.f90
  - ARONNAX_TEST_VALGRIND_ALL=1 pytest --cov=aronnax
#  - bash <(curl -s https://codecov.io/bash) -cF python

after_success:
#  - lcov --compat-libtool --directory . --capture --output-file coverage.info
#  - coveralls-lcov -v -n coverage.info > coverage.json
#  - coveralls --merge=coverage.json
  - codecov
  - bash <(curl -s https://codecov.io/bash)
  - cd benchmarks
  - python benchmark.py
  - cd ../docs
  - make html
  - cd _build/html


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_token # Set in travis-ci.org dashboard
  on:
    branch: master