
language: python
python:
  - "2.7"

sudo: required

branches:
  only:

before_install: 
  - sudo apt-get install gfortran
  - sudo apt-get install valgrind
  - pip install scipy
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install recommonmark
  - pip install matplotlib
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install cpp-coveralls
  - pip install -e .

install: 

script:
  - gfortran -Wall -Werror aronnax.f90
  - ARONNAX_TEST_VALGRIND_ALL=1 pytest --cov=aronnax

after_success:
  - gcov aronnax.gcda > coverage.json
  - coveralls --merge=coverage.json
  - cd benchmarks
  - python benchmark.py
  - cd ../docs
  - make html
  - cd _build/html


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_token # Set in travis-ci.org dashboard
  on:
    branch: master