language: python
python:
  - "2.7"

sudo: required

branches:
  only:

before_install: 
  - sudo apt-get install gfortran
  - sudo apt-get install valgrind
  - cd $TRAVIS_BUILD_DIR/utils
  - python setup.py install

install: "pip install scipy"

script:
  - pytest

after_success:
