language: python
python:
  - "2.7"

sudo: required

branches:
  only:

before_install: 
  - sudo apt-get install gfortran
  - sudo apt-get install valgrind
  - sudo apt-get install libopenmpi-dev
  - sudo apt-get install openmpi-bin
  - sudo apt-get install libhypre-dev
  - pip install scipy
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install recommonmark
  - pip install matplotlib
  - pip install -e .

install: 

script:
  - mpif90 -Werror aronnax.f90 -cpp
  - pytest

after_success:
  - cd benchmarks
  - python benchmark.py
  - cd ../docs
  - make html
  - cd _build/html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_token # Set in travis-ci.org dashboard
  on:
    branch: master
