language: python
python:
  - "2.7"

sudo: required

branches:
  only:

before_install: 
  - sudo apt-get install gfortran
  - sudo apt-get install valgrind
  - cd $TRAVIS_BUILD_DIR/utils
  - python setup.py install
  - cd $TRAVIS_BUILD_DIR

install: "pip install scipy"

script:
  - gfortran -Wall -Werror aronnax.f90
  - ARONNAX_TEST_VALGRIND_ALL=1 pytest

after_success:
