language: python
python:
  - "2.7"

sudo: required

branches:
  only:

before_install: 
  - sudo apt-get install gfortran
  - sudo apt-get install valgrind
  - pip install scipy
  - python setup.py install

install: 

script:
  - gfortran -Werror aronnax.f90 -cpp
  - ARONNAX_TEST_VALGRIND_ALL=1 pytest

after_success:
