language: python
python:
  - "2.6"
  - "2.7"

sudo: required

branches:
  only:

before_install: 
  - sudo apt-get install gfortran
  - sudo apt-get install valgrind

install: "pip install scipy"

script:
  - pytest

after_success:
